### ISSUE TITLE
Pkg name

### ISSUE THREAD

**Issue by dmetivie** [JuliaDynamics/StreamSampling.jl#60]
I found this doc link [IteratorSampling.jl](https://juliadynamics.github.io/StreamSampling.jl/stable/) where the package is called IteratorSampling and in the confusion I was able to `add IteratorSampling`. 
However `add StreamSampling` does not work and the dev doc [StreamSampling.jl](https://juliadynamics.github.io/StreamSampling.jl/dev/) seem less complete.
What is the correct package name (I am guessing StreamSampling)?

**Comment by Tortar** [comment]
Sorry for that, I'm in the process of registering it as a rename as I commented in the other issue, do you find the API page https://juliadynamics.github.io/StreamSampling.jl/dev/api/ less complete than the previous one?  

To try to avoid confusion for other people, let's keep this open until the new renamed package is out

**Comment by dmetivie** [comment]
No my bad it is the same plus another tab!

**Comment by Tortar** [comment]
It was registered some time ago, so we can close this one!
